### ISSUE TITLE
Difference between allowed data supplied to WSMA and FasterWSMA

### ISSUE THREAD

**Issue by parapants** [bennycode/trading-signals#369]
This is minor.  WSMA allows numbers contained in strings and FasterWSMA does not.  I ran into the issue switching between the two of them.   Adding a parseFloat to my data allowed FasterWSMA to work correctly.

Thank you for the work you have done.  It has been very helpful.

**Comment by bennycode** [comment]
Hi @parapants, I am happy to hear that you like this library. The `FasterWSMA` class is made for high performance which is why it does not parse the input but expects it to be of type `number`. When working with TypeScript you will actually see that because TypeScript warns you when passing strings to a function which expects numbers. I can really recommend you to checkout TypeScript. Happy Trading! Benny
